import Header from './components/Header'
import Hydrate from './components/Hydrate'
import './globals.css'
import { Goldman, Play } from "@next/font/google"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const goldman = Goldman({
  subsets: ['latin'],
  display: 'swap',
  weight: ['700'],
  variable: '--font-goldman'
})

const play = Play({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-play'
})





export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en" className={`${play.variable}`}>
      <body className={`${goldman.variable}`}>
        <Hydrate>
        <Header />
        {children}
        </Hydrate>
        </body>
    </html>
  )
}
